version: '3.1'

services:
  db_postgresql:
    image: postgres:16.2
    container_name: db_restaurants
    restart: always
    environment:
      - POSTGRES_DB=db_restaurants
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
